In [1]:
from scipy import stats
import numpy as np
import numpy as np
from scipy.interpolate import splprep, splev
import matplotlib.pyplot as plt

In [5]:
data = stats.norm.rvs(size=1000, loc=10, scale=1)

hist = np.histogram(data, bins=5)

hist_dist = stats.rv_histogram(hist)

hist_dist.cdf(12)

0.9665571257041679

In [73]:
from etc_jupyterlab_distribution import DistributionWidget

distWidget = DistributionWidget()

distWidget

DistributionWidget(value=None)

In [55]:
distWidget.value.cdf(400)

0.6987045918040704

In [83]:
X = np.array([int(key) for key in distWidget.coord.keys()])

Y = np.array([int(key) for key in distWidget.coord.values()])

pts = np.vstack((X, Y))

tck, u = splprep(pts, s=0.0)

u_new = np.linspace(u.min(), u.max(), 10000)

x, y = splev(u_new, tck)

data = np.repeat(x, np.ceil(y).astype(int))

hist = np.histogram(data, bins=5)

# hist_dist = stats.rv_histogram(hist)

# fig, ax = plt.subplots(1, 1)

# test = plt.plot(x, y, 'b--')

# ax.set_ylim(0,y.max() + 100)

# plt.show()

hist

(array([169392, 238247, 238417, 219920, 162791]),
 array([ 49. , 127.2, 205.4, 283.6, 361.8, 440. ]))

In [39]:
hist_dist.cdf(200)

In [62]:
from scipy.interpolate import interp1d
fst = np.array([4, 4, 1, 3, 1, 4, 3, 2, 5, 2])
snd = np.array([1, 1, 3, 4, 1, 5, 5, 5, 4, 3])
linfit = interp1d([1,5], np.vstack([fst, snd]), axis=0)
linfit(4)

array([1.75, 1.75, 2.5 , 3.75, 1.  , 4.75, 4.5 , 4.25, 4.25, 2.75])

In [81]:
Y = np.array([1, 1, 3, 4, 1, 5, 5, 5, 4, 3])
X = np.array([1, 5, 10, 30, 32, 36, 3, 2, 5, 2])
np.interp(range(X.min(), X.max()+1), X, Y)

array([1., 1., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3.])