In [1]:
from scipy import stats
import numpy as np
import numpy as np
from scipy.interpolate import splprep, splev
import matplotlib.pyplot as plt

In [4]:
from etc_jupyterlab_distribution import DistributionWidget

distWidget = DistributionWidget()

distWidget

DistributionWidget(value=None)

In [9]:
distWidget.value.cdf(400)

0.4129118156157645

In [22]:
data = stats.norm.rvs(size=1000, loc=10, scale=1)

hist = np.histogram(data, bins=5)

hist_dist = stats.rv_histogram(hist)

hist_dist.cdf(12)

hist

(array([ 58, 297, 459, 171,  15]),
 array([ 7.07973338,  8.35352767,  9.62732195, 10.90111623, 12.17491051,
        13.44870479]))

In [5]:
type(hist_dist)

scipy.stats._continuous_distns.rv_histogram

In [7]:
# stats.rv_histogram(hist)

In [42]:


hist_dist.cdf(400)

0.9517628588209462

In [40]:
pts

array([[ 72,  73,  74,  75,  77,  82,  83,  88,  96,  97, 105, 113, 116,
        119, 120, 127, 130, 131, 132, 135, 138, 143, 146, 148, 153, 159,
        162, 164, 187, 192, 214, 236, 245, 250, 267, 278, 295, 300, 318,
        324, 330, 333, 342, 356, 372, 374, 380, 382, 397, 403, 406, 416,
        419, 420, 430, 431, 433],
       [ 40,  41,  43,  46,  49,  62,  64,  73,  87,  90, 100, 111, 114,
        117, 118, 128, 129, 131, 131, 133, 136, 138, 139, 139, 141, 142,
        142, 142, 142, 142, 139, 136, 136, 134, 132, 128, 119, 118, 108,
        104, 101,  98,  93,  81,  72,  71,  67,  66,  54,  50,  47,  40,
         37,  34,  27,  26,  23]])